name: Update GitHub Activity Graph

on:
  schedule:
    # Update every 6 hours
    - cron: "17 */6 * * *"

  # Allows you to manually run it from Actions
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Generate activity graph
        uses: maurodesouza/github-readme-activity-graph-action@v1
        with:
          username: nivijha

          # Tokyo Night style
          options: >-
            theme=tokyo-night
            &hide_border=true
            &area=true
            &radius=12
            &height=350
            &days=31
            &grid=true

          output_path: dist/activity-graph.svg

          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish generated graph
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          build_dir: dist
          target_branch: output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}